### ISSUE TITLE
filename的问题

### ISSUE THREAD

**Issue by LoganJunjieSheng** [jiangli373/WinStonDemo#1]
请问如何在log.js中设置filename

**Comment by jiangli373** [comment]
```
var logger = new (winston.Logger)({
    transports: [
        new (winston.transports.File)({
            filename: __dirname+'/logs/detaillog.log',
            maxsize:102400,
            maxFiles:10
        })
    ],
    exceptionHandlers: [
        new winston.transports.File({
            filename: __dirname+'/logs/exceptions.log',
            handleExceptions: true
        })
    ],
    exitOnError: false
});
```

**Comment by LoganJunjieSheng** [comment]
你好，再请教一下我对于filename的路径有点疑问；
我现在~/logs/config.js中配置的如下代码
var winston=require('winston');
var logger = winston.createLogger({
    level:'info',
    format:winston.format.json(),
    transports: [
        new winston.transports.Console(),
        new winston.transports.File({
            filename:‘这里有疑问’,
            timestamp:'true',
            maxsize: 10485760,
            maxFiles: 10 })
    ]});

exports.logger=logger;
想在别处调用logger的时候将日志写入~/logs/test.log中，尝试了各种路径配种都没办法写入，但console中能够成功输入，请问filename的路径如何配

**Comment by jiangli373** [comment]
filename: __dirname+ 'test.log'  这样就可以吧

**Comment by LoganJunjieSheng** [comment]
感恩感恩，终于成功了！改正一下应该是filename: __dirname+ '/test.log'
如果是filename: __dirname+ 'test.log' 这样子会在根目录下创建一个xxx.log的文件

**Comment by jiangli373** [comment]
嗯，上面写错了；__dirname是指的当前目录
